name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install and test modules
      run: mvn clean install -DskipTests -pl ch-commons-util -am

    - name: Run normally
      run:  mvn -pl ch-commons-util test -Dtest=com.cloudhopper.commons.util.MetaFieldUtilTest#toMetaFieldInfoArray

    - name: Run tests with NonDex
      run: mvn -pl ch-commons-util edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.cloudhopper.commons.util.MetaFieldUtilTest#toMetaFieldInfoArray
